ads04 hometask
NabiyevTR/ads04 pull request #1
Opened 2021-02-14 06:36 UTC by NabiyevTR

2021-02-17 22:13 UTC, OKrylov requested changes
В целом все хорошо, но обратите внимание на замечания

2021-02-17 22:13 UTC, OKrylov commented on src/ru/geekbrains/ntr_ads04/library/SimpleLinkedListImpl.java
> +                    return currentElement.next != null;
а если список состоит из одного элемента?

2021-02-17 22:13 UTC, OKrylov commented on src/ru/geekbrains/ntr_ads04/library/SimpleLinkedListImpl.java
> +                    return currentElement.next != null;
Следует проверять только currentElement, его же значение возвращать в next

2021-02-18 04:56 UTC, NabiyevTR commented on src/ru/geekbrains/ntr_ads04/library/SimpleLinkedListImpl.java
> +                    return currentElement.next != null;
Спасибо. Понял.

2021-07-20 20:57 UTC, merged